version: '3.4'

services:
  usermanagement.server:
    image: ${DOCKER_REGISTRY-}usermanagementserver
    build:
      context: .
      dockerfile: UserManagement.Server/Dockerfile

  sql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=P@ssword
    ports:
      - "1433:1433"
    volumes:
      - sql-server:/var/opt/mssql

volumes:
  sql-server:
